import { PrismaClient, Prisma } from '@prisma/client'
import { Request, Response } from 'express'
import { RawJob } from '~/types/job'

import { urls } from '~/pages/api/icons/urls'

//requires API_KEY to be set

//requires DATABASE_URL to be set
const prisma = new PrismaClient()

const images = [
  'nomad.png',
  'swift.png',
  'buildkite.png',
  'bash.png',
  'kibana.png',
  'blockchain.png',
  'adwords.png',
  'dragonfly.png',
  'eks.png',
  'drip.png',
  'hotjar.png',
  'knockout.png',
  'mongodb.png',
  'vue.png',
  'wagtail.png',
  'cloudfront.png',
  'symfony.png',
  'javascript.png',
  'angular.png',
  'cocoon.png',
  'rds.png',
  'squarespace.png',
  'metamask.pn g',
  'swagger.png',
  'mongo.png',
  'cordova.png',
  'mux.png',
  'protobuf.png',
  'lambda.png',
  'jenkins.png',
  'prometheus.png',
  'salesforce.png',
  'phpunit.png',
  'contentful.png',
  'protractor.png',
  'consul.png',
  'jira.png',
  'phoenix.png',
  'aws.png',
  'jupyter.png',
  'ios.png',
  'ktor.png',
  'rails.png',
  'beanstalk.png',
  'android.pn g',
  'vuex.png',
  'zeplin.png',
  'react.png',
  'ancestry.png',
  'fargate.png',
  'redis.png ',
  'statsd.png',
  'nft.png',
  'asp.png',
  'kafka.png',
  'cypress.png',
  'python.png',
  'backbone.png',
  'fastapi.png',
  'elasticache.png',
  'karma.png',
  'maven.png',
  'k8s.png',
  'fortran.png',
  'origami.png',
  'sketch.png',
  'element.png',
  'kubernetes.png',
  'nestjs.png',
  'cassandra.png',
  'puppet.png',
  'couchdb.png',
  'nlp.png',
  'seo.png',
  'postgres.png',
  'electron.png',
  'crud.png',
  'gitlab.png',
  'sqlite.png',
  'memcache.png',
  'maze.png',
  'ux.png',
  'elixir.png',
  'rq.png',
  'ecs.png',
  'node.png',
  'nginx.png',
  'express.png',
  'guardian.png',
  'wordpress.png',
  'postgresql.png',
  'tailwind.png',
  'cryptocurrency.png',
  'dynamodb.png',
  'atlassian.png',
  'keras.png',
  'helm.png',
  'postcss.png',
  'composer.png',
  'rhel.png',
  'flink.png',
  'jquery.png',
  'web3.png',
  'moz.png',
  'embedded.png',
  'qa.png',
  'sentry.png',
  'moment.png',
  'nodejs.png',
  'ethereum.png',
  'travis.png',
  'stark.png',
  'salt.png',
  'scala.png',
  'jwt.png',
  'net.png',
  'voyager.png',
  'absinthe.png',
  'typescript.png',
  'argo.png',
  'apache.png',
  'tomcat.png',
  'phantom. png',
  'nosql.png',
  'hibernate.png',
  'flask.png',
  'invision.png',
  'kotlin.png',
  'pagerduty.png',
  'rabbitmq.png',
  'oracle.png',
  'etl.png',
  'hyper.png',
  'containers.png',
  'graphql.png',
  'gin.png',
  'golang.png',
  'perl.png',
  'pandas.png',
  'cargo.png',
  'drf. png',
  'clojure.png',
  'kong.png',
  'protopie.png',
  'hubspot.png',
  'tailwindcss.png',
  'wix.png',
  'selenium.png',
  'confluence.png',
  'elm.png',
  'redux.png',
  'actix.png',
  'un ix.png',
  'erlang.png',
  'sql.png',
  'heroku.png',
  'rust.png',
  'ledger.png',
  'flutter.p ng',
  'ember.png',
  'stimulus.png',
  'solidity.png',
  'github.png',
  'gcp.png',
  'grunt.pn g',
  'figma.png',
  'mocha.png',
  'illustrator.png',
  'yaml.png',
  'terraform.png',
  'rocke t.png',
  'restful.png',
  'tensorflow.png',
  'photoshop.png',
  'spring.png',
  'rspec.png',
  'ahrefs.png',
  'pytorch.png',
  'bootstrap.png',
  'hapi.png',
  'grafana.png',
  'spark.png ',
  'coverage.png',
  'istanbul.png',
  'scipy.png',
  'embark.png',
  's3.png',
  'docker.png',
  'laravel.png',
  'ansible.png',
  'enzyme.png',
  'mesos.png',
  'fintech.png',
  'hyperledg er.png',
  'chef.png',
  'netty.png',
  'serverless.png',
  'ml.png',
  'elasticsearch.png',
  ' knative.png',
  'mailchimp.png',
  'mysql.png',
  'cortex.png',
  'codeigniter.png',
  'babel. png',
  'azure.png',
  'neo4j.png',
  'datadog.png',
  'formik.png',
  'jekyll.png',
  'bitcoin. png',
  'travisci.png',
  'gunicorn.png',
  'cloudformation.png',
  'ionic.png',
  'haskell.pn g',
  'sidekiq.png',
  'jasmine.png',
  'hadoop.png',
  'pyramid.png',
  'loki.png',
  'vpc.png',
  'php.png',
  'indesign.png',
  'digitalocean.png',
  'svelte.png',
  'drupal.png',
  'infose c.png',
  'celery.png',
  'junit.png',
  'haproxy.png',
  'cobra.png',
  'devise.png',
  'parity .png',
  'ipfs.png',
  'grpc.png',
  'gatsby.png',
  'mesos.webp',
  'pillow.png',
  'vscode.png ',
  'semrush.png',
  'cloudflare.png',
  'axios.png',
  'scikit.png',
  'ruby.png',
  'openapi.png',
  'sns.png',
  'sqlalchemy.png',
  'django.png',
  'revel.png',
  'iconic.png',
  'jest.pn g',
  'apollo.png',
  'nest.png',
  'arrow.png',
  'saltstack.png',
  'circleci.png',
  'hci.png ',
  'numpy.png',
  'marvel.png',
  'diesel.png',
  'activeadmin.png',
  'openstack.png',
]

const fetchDocs = async function () {
  // get all the skills from the database
  const skills = await prisma.skill.findMany()
  // remove the spaces from all the images
  const imagesClean = images.map((image) => image.replace(' ', ''))

  // update every skill with the url
  for (const skill of skills) {
    // const url = urls.find((url) => url.name === skill.name)
    if (imagesClean.includes(`${skill.name}.png`)) {
      console.log(skill.name)
      await prisma.skill.update({
        where: {
          name: skill.name,
        },
        data: {
          icon: skill.name + '.png',
        },
      })
    }
  }
}

export default async function handler(req: Request, res: Response) {
  const skills = await fetchDocs()
  res.status(200).json({ message: 'success', skills: skills })
}
